---
- name: Create the main user.
  user:
    name: adam
    group: admin adm
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    uid: 1001
    update_password: {{ adam_password }}
